server:
  name: 'mcp-context-server'
  version: '1.0.0'

security:
  allowedCommands:
    - 'ls'
    - 'cat'
    - 'grep'
    - 'find'
    - 'git'
  safezones:
    - '/app/workspace'
    - '/tmp'
  maxExecutionTime: 30000
  maxFileSize: 10485760

database:
  path: '/data/context.db'
  backupInterval: 30 # More frequent backups in production

logging:
  level: 'info'
  pretty: false # Structured logging in production

performance:
  maxConcurrency: 20
  queueSize: 2000
